version: '3.8'

services:
    app-fotouley:
        build:
            context: .
            dockerfile: docker/php/Dockerfile.php
        image: fotouley-app-image
        container_name: fotouley-app
        restart: unless-stopped
        tty: true
        environment:
        - "DB_PORT=${DB_PORT}"
        - "DB_HOST=${DB_HOST}"
        working_dir: /var/www
        networks:
        - fotouley-network
        volumes:
        - .:/var/www

    nginx-fotouley:
        image: nginx:alpine
        container_name: fotouley-nginx
        restart: unless-stopped
        tty: true
        ports:
        - "805:80"
        
        networks:
        - fotouley-network
        volumes:
        - .:/var/www
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        

    mysql-fotouley:
        image: mysql:8.0
        container_name: ${DB_HOST}
        restart: unless-stopped
        tty: true
        ports:
        - "33065:3306"
        networks:
        - fotouley-network
        environment:
        - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
        - "MYSQL_USER=${DB_USERNAME}"
        - "MYSQL_PASSWORD=${DB_PASSWORD}"
        - "MYSQL_DATABASE=${DB_DATABASE}"
        - "MYSQL_TCP_PORT=${DB_PORT}"
        volumes:
        - ./docker/mysql/db:/var/lib/mysql

networks:
    fotouley-network:
        driver: bridge
